#!/usr/bin/env python3
import json,pathlib
root=pathlib.Path(__file__).resolve().parents[2]; api=root/'operator/api/v1alpha1'; api.mkdir(parents=True,exist_ok=True)
out=root/'operator/config/crd/bases';out.mkdir(parents=True,exist_ok=True)
types=[]
def ident(s):
 for a,b in [('gpuUUID','GPUUUID'),('vmiUID','VMIUID'),('workerPodUID','WorkerPodUID'),('podUID','PodUID'),('reporterPodUID','ReporterPodUID'),('launcherPodUID','LauncherPodUID'),('uid','UID'),('gid','GID')]:
  if s==a:return b
 return s[0].upper()+s[1:]
def struct(name,schema):
 lines=[]
 for k,v in schema.get('properties',{}).items():
  t=v.get('type'); typ={'string':'string','integer':'int64','boolean':'bool'}.get(t)
  if t=='object':typ=name+ident(k);struct(typ,v)
  elif t=='array':
   if v['items'].get('type')=='object':typ='[]'+name+ident(k)+'Item';struct(typ[2:],v['items'])
   else:typ='[]string'
  if not typ:raise ValueError((k,v))
  suffix='' if k in schema.get('required',[]) else ',omitempty'
  lines.append(f'{ident(k)} {typ} `json:"{k}{suffix}"`')
 types.append('type '+name+' struct {\n'+'\n'.join(lines)+'\n}')
for p in sorted(out.glob('*.json')):
 c=json.loads(p.read_text())
 s=c['spec'];kind=s['names']['kind']
 props=s['versions'][0]['schema']['openAPIV3Schema']['properties']
 for field in ['spec','status']:struct(kind+field.title(),props[field])
 types.append('// +kubebuilder:object:root=true\n// +kubebuilder:subresource:status\ntype '+kind+' struct {\nmetav1.TypeMeta `json:",inline"`\nmetav1.ObjectMeta `json:"metadata,omitempty"`\nSpec '+kind+'Spec `json:"spec"`\nStatus '+kind+'Status `json:"status,omitempty"`\n}')
 types.append('// +kubebuilder:object:root=true\ntype '+kind+'List struct {\nmetav1.TypeMeta `json:",inline"`\nmetav1.ListMeta `json:"metadata,omitempty"`\nItems []'+kind+' `json:"items"`\n}')
(api/'types.go').write_text('// Code generated by hack/generate-types.py from canonical schemas. DO NOT EDIT.\npackage v1alpha1\nimport metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"\n'+ '\n'.join(types))
(api/'groupversion_info.go').write_text('''// +kubebuilder:object:generate=true
// +groupName=vmweave.io
package v1alpha1
import (
 "k8s.io/apimachinery/pkg/runtime/schema"
 "sigs.k8s.io/controller-runtime/pkg/scheme"
)
var GroupVersion = schema.GroupVersion{Group:"vmweave.io", Version:"v1alpha1"}
var SchemeBuilder = &scheme.Builder{GroupVersion:GroupVersion}
var AddToScheme = SchemeBuilder.AddToScheme
func init(){ SchemeBuilder.Register(&GPUProfile{}, &GPUProfileList{}, &GPURequest{}, &GPURequestList{}, &SharedMemoryChannel{}, &SharedMemoryChannelList{}, &ChannelAttachment{}, &ChannelAttachmentList{}) }
''')
