// Code generated by hack/generate-types.py from canonical schemas. DO NOT EDIT.
package v1alpha1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

type ChannelAttachmentSpecChannelRef struct {
	Name string `json:"name"`
	UID  string `json:"uid"`
}
type ChannelAttachmentSpec struct {
	ChannelRef ChannelAttachmentSpecChannelRef `json:"channelRef"`
	Generation string                          `json:"generation"`
	Role       string                          `json:"role"`
	HolderUID  string                          `json:"holderUID"`
	NodeName   string                          `json:"nodeName"`
}
type ChannelAttachmentStatus struct {
	Phase              string `json:"phase,omitempty"`
	Evidence           string `json:"evidence,omitempty"`
	ReporterPodUID     string `json:"reporterPodUID,omitempty"`
	LauncherPodUID     string `json:"launcherPodUID,omitempty"`
	ObservedGeneration int64  `json:"observedGeneration,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ChannelAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ChannelAttachmentSpec   `json:"spec"`
	Status            ChannelAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type ChannelAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ChannelAttachment `json:"items"`
}
type GPUProfileSpec struct {
	Approved      bool   `json:"approved,omitempty"`
	NodeName      string `json:"nodeName"`
	GPUUUID       string `json:"gpuUUID"`
	Cores         int64  `json:"cores"`
	MemoryMiB     int64  `json:"memoryMiB"`
	MaxClients    int64  `json:"maxClients,omitempty"`
	WorkerImage   string `json:"workerImage"`
	RuntimeClass  string `json:"runtimeClass,omitempty"`
	HamiNamespace string `json:"hamiNamespace"`
	SchedulerName string `json:"schedulerName,omitempty"`
}
type GPUProfileStatusConditionsItem struct {
	Type               string `json:"type"`
	Status             string `json:"status"`
	LastTransitionTime string `json:"lastTransitionTime"`
	Reason             string `json:"reason"`
	Message            string `json:"message"`
	ObservedGeneration int64  `json:"observedGeneration,omitempty"`
}
type GPUProfileStatus struct {
	ObservedGeneration int64                            `json:"observedGeneration,omitempty"`
	Phase              string                           `json:"phase,omitempty"`
	Conditions         []GPUProfileStatusConditionsItem `json:"conditions,omitempty"`
	Consumers          int64                            `json:"consumers,omitempty"`
	Endpoint           string                           `json:"endpoint,omitempty"`
	PodUID             string                           `json:"podUID,omitempty"`
	PodIP              string                           `json:"podIP,omitempty"`
	VmIP               string                           `json:"vmIP,omitempty"`
	WorkerGeneration   string                           `json:"workerGeneration,omitempty"`
	ManagerEpoch       string                           `json:"managerEpoch,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type GPUProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GPUProfileSpec   `json:"spec"`
	Status            GPUProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GPUProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GPUProfile `json:"items"`
}
type GPURequestSpecVmRef struct {
	Name string `json:"name"`
	UID  string `json:"uid"`
}
type GPURequestSpecProfileRef struct {
	Name string `json:"name"`
	UID  string `json:"uid"`
}
type GPURequestSpec struct {
	VmRef      GPURequestSpecVmRef      `json:"vmRef"`
	ProfileRef GPURequestSpecProfileRef `json:"profileRef"`
	Count      int64                    `json:"count"`
	Compute    int64                    `json:"compute"`
	Memory     string                   `json:"memory"`
}
type GPURequestStatusConditionsItem struct {
	Type               string `json:"type"`
	Status             string `json:"status"`
	LastTransitionTime string `json:"lastTransitionTime"`
	Reason             string `json:"reason"`
	Message            string `json:"message"`
	ObservedGeneration int64  `json:"observedGeneration,omitempty"`
}
type GPURequestStatusRequested struct {
	Count     int64 `json:"count"`
	Compute   int64 `json:"compute"`
	MemoryMiB int64 `json:"memoryMiB"`
}
type GPURequestStatusApplied struct {
	Count     int64 `json:"count"`
	Compute   int64 `json:"compute"`
	MemoryMiB int64 `json:"memoryMiB"`
}
type GPURequestStatusWorkerRef struct {
	Name string `json:"name"`
	UID  string `json:"uid"`
}
type GPURequestStatusVmiRef struct {
	Name string `json:"name"`
	UID  string `json:"uid"`
}
type GPURequestStatus struct {
	ObservedGeneration       int64                            `json:"observedGeneration,omitempty"`
	Phase                    string                           `json:"phase,omitempty"`
	Conditions               []GPURequestStatusConditionsItem `json:"conditions,omitempty"`
	Consumers                int64                            `json:"consumers,omitempty"`
	Endpoint                 string                           `json:"endpoint,omitempty"`
	PodUID                   string                           `json:"podUID,omitempty"`
	PodIP                    string                           `json:"podIP,omitempty"`
	VmIP                     string                           `json:"vmIP,omitempty"`
	WorkerGeneration         string                           `json:"workerGeneration,omitempty"`
	ManagerEpoch             string                           `json:"managerEpoch,omitempty"`
	Requested                GPURequestStatusRequested        `json:"requested,omitempty"`
	Applied                  GPURequestStatusApplied          `json:"applied,omitempty"`
	AppliedRequestGeneration int64                            `json:"appliedRequestGeneration,omitempty"`
	WorkerRef                GPURequestStatusWorkerRef        `json:"workerRef,omitempty"`
	VmiRef                   GPURequestStatusVmiRef           `json:"vmiRef,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type GPURequest struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GPURequestSpec   `json:"spec"`
	Status            GPURequestStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type GPURequestList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GPURequest `json:"items"`
}
type SharedMemoryChannelSpecVmRef struct {
	Name string `json:"name"`
	UID  string `json:"uid"`
}
type SharedMemoryChannelSpecRequestRef struct {
	Name string `json:"name"`
	UID  string `json:"uid"`
}
type SharedMemoryChannelSpecPvcRef struct {
	Name string `json:"name"`
	UID  string `json:"uid"`
}
type SharedMemoryChannelSpec struct {
	VmRef       SharedMemoryChannelSpecVmRef      `json:"vmRef"`
	RequestRef  SharedMemoryChannelSpecRequestRef `json:"requestRef"`
	PvcRef      SharedMemoryChannelSpecPvcRef     `json:"pvcRef"`
	Sessions    int64                             `json:"sessions"`
	UID         int64                             `json:"uid"`
	GID         int64                             `json:"gid"`
	Image       string                            `json:"image"`
	WorkerImage string                            `json:"workerImage"`
	HookImage   string                            `json:"hookImage"`
	Drain       bool                              `json:"drain,omitempty"`
}
type SharedMemoryChannelStatusConditionsItem struct {
	Type               string `json:"type"`
	Status             string `json:"status"`
	Reason             string `json:"reason"`
	Message            string `json:"message"`
	LastTransitionTime string `json:"lastTransitionTime"`
	ObservedGeneration int64  `json:"observedGeneration"`
}
type SharedMemoryChannelStatus struct {
	Phase              string                                    `json:"phase,omitempty"`
	Reason             string                                    `json:"reason,omitempty"`
	Allocation         string                                    `json:"allocation,omitempty"`
	Generation         string                                    `json:"generation,omitempty"`
	NodeName           string                                    `json:"nodeName,omitempty"`
	GPUUUID            string                                    `json:"gpuUUID,omitempty"`
	VMIUID             string                                    `json:"vmiUID,omitempty"`
	WorkerPodUID       string                                    `json:"workerPodUID,omitempty"`
	Mode               string                                    `json:"mode,omitempty"`
	ObservedGeneration int64                                     `json:"observedGeneration,omitempty"`
	MemoryMiB          int64                                     `json:"memoryMiB,omitempty"`
	Compute            int64                                     `json:"compute,omitempty"`
	RequestGeneration  int64                                     `json:"requestGeneration,omitempty"`
	ProfileGeneration  int64                                     `json:"profileGeneration,omitempty"`
	EverBound          bool                                      `json:"everBound,omitempty"`
	Sessions           []string                                  `json:"sessions,omitempty"`
	Conditions         []SharedMemoryChannelStatusConditionsItem `json:"conditions,omitempty"`
	ResourcePrefix     string                                    `json:"resourcePrefix,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type SharedMemoryChannel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SharedMemoryChannelSpec   `json:"spec"`
	Status            SharedMemoryChannelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type SharedMemoryChannelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SharedMemoryChannel `json:"items"`
}
