//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelAttachment) DeepCopyInto(out *ChannelAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelAttachment.
func (in *ChannelAttachment) DeepCopy() *ChannelAttachment {
	if in == nil {
		return nil
	}
	out := new(ChannelAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChannelAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelAttachmentList) DeepCopyInto(out *ChannelAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChannelAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelAttachmentList.
func (in *ChannelAttachmentList) DeepCopy() *ChannelAttachmentList {
	if in == nil {
		return nil
	}
	out := new(ChannelAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChannelAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelAttachmentSpec) DeepCopyInto(out *ChannelAttachmentSpec) {
	*out = *in
	out.ChannelRef = in.ChannelRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelAttachmentSpec.
func (in *ChannelAttachmentSpec) DeepCopy() *ChannelAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(ChannelAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelAttachmentSpecChannelRef) DeepCopyInto(out *ChannelAttachmentSpecChannelRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelAttachmentSpecChannelRef.
func (in *ChannelAttachmentSpecChannelRef) DeepCopy() *ChannelAttachmentSpecChannelRef {
	if in == nil {
		return nil
	}
	out := new(ChannelAttachmentSpecChannelRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChannelAttachmentStatus) DeepCopyInto(out *ChannelAttachmentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChannelAttachmentStatus.
func (in *ChannelAttachmentStatus) DeepCopy() *ChannelAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(ChannelAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUProfile) DeepCopyInto(out *GPUProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUProfile.
func (in *GPUProfile) DeepCopy() *GPUProfile {
	if in == nil {
		return nil
	}
	out := new(GPUProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUProfileList) DeepCopyInto(out *GPUProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUProfileList.
func (in *GPUProfileList) DeepCopy() *GPUProfileList {
	if in == nil {
		return nil
	}
	out := new(GPUProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUProfileSpec) DeepCopyInto(out *GPUProfileSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUProfileSpec.
func (in *GPUProfileSpec) DeepCopy() *GPUProfileSpec {
	if in == nil {
		return nil
	}
	out := new(GPUProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUProfileStatus) DeepCopyInto(out *GPUProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]GPUProfileStatusConditionsItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUProfileStatus.
func (in *GPUProfileStatus) DeepCopy() *GPUProfileStatus {
	if in == nil {
		return nil
	}
	out := new(GPUProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUProfileStatusConditionsItem) DeepCopyInto(out *GPUProfileStatusConditionsItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUProfileStatusConditionsItem.
func (in *GPUProfileStatusConditionsItem) DeepCopy() *GPUProfileStatusConditionsItem {
	if in == nil {
		return nil
	}
	out := new(GPUProfileStatusConditionsItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequest) DeepCopyInto(out *GPURequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequest.
func (in *GPURequest) DeepCopy() *GPURequest {
	if in == nil {
		return nil
	}
	out := new(GPURequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPURequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestList) DeepCopyInto(out *GPURequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPURequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestList.
func (in *GPURequestList) DeepCopy() *GPURequestList {
	if in == nil {
		return nil
	}
	out := new(GPURequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPURequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestSpec) DeepCopyInto(out *GPURequestSpec) {
	*out = *in
	out.VmRef = in.VmRef
	out.ProfileRef = in.ProfileRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestSpec.
func (in *GPURequestSpec) DeepCopy() *GPURequestSpec {
	if in == nil {
		return nil
	}
	out := new(GPURequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestSpecProfileRef) DeepCopyInto(out *GPURequestSpecProfileRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestSpecProfileRef.
func (in *GPURequestSpecProfileRef) DeepCopy() *GPURequestSpecProfileRef {
	if in == nil {
		return nil
	}
	out := new(GPURequestSpecProfileRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestSpecVmRef) DeepCopyInto(out *GPURequestSpecVmRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestSpecVmRef.
func (in *GPURequestSpecVmRef) DeepCopy() *GPURequestSpecVmRef {
	if in == nil {
		return nil
	}
	out := new(GPURequestSpecVmRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestStatus) DeepCopyInto(out *GPURequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]GPURequestStatusConditionsItem, len(*in))
		copy(*out, *in)
	}
	out.Requested = in.Requested
	out.Applied = in.Applied
	out.WorkerRef = in.WorkerRef
	out.VmiRef = in.VmiRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestStatus.
func (in *GPURequestStatus) DeepCopy() *GPURequestStatus {
	if in == nil {
		return nil
	}
	out := new(GPURequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestStatusApplied) DeepCopyInto(out *GPURequestStatusApplied) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestStatusApplied.
func (in *GPURequestStatusApplied) DeepCopy() *GPURequestStatusApplied {
	if in == nil {
		return nil
	}
	out := new(GPURequestStatusApplied)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestStatusConditionsItem) DeepCopyInto(out *GPURequestStatusConditionsItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestStatusConditionsItem.
func (in *GPURequestStatusConditionsItem) DeepCopy() *GPURequestStatusConditionsItem {
	if in == nil {
		return nil
	}
	out := new(GPURequestStatusConditionsItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestStatusRequested) DeepCopyInto(out *GPURequestStatusRequested) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestStatusRequested.
func (in *GPURequestStatusRequested) DeepCopy() *GPURequestStatusRequested {
	if in == nil {
		return nil
	}
	out := new(GPURequestStatusRequested)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestStatusVmiRef) DeepCopyInto(out *GPURequestStatusVmiRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestStatusVmiRef.
func (in *GPURequestStatusVmiRef) DeepCopy() *GPURequestStatusVmiRef {
	if in == nil {
		return nil
	}
	out := new(GPURequestStatusVmiRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPURequestStatusWorkerRef) DeepCopyInto(out *GPURequestStatusWorkerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPURequestStatusWorkerRef.
func (in *GPURequestStatusWorkerRef) DeepCopy() *GPURequestStatusWorkerRef {
	if in == nil {
		return nil
	}
	out := new(GPURequestStatusWorkerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedMemoryChannel) DeepCopyInto(out *SharedMemoryChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedMemoryChannel.
func (in *SharedMemoryChannel) DeepCopy() *SharedMemoryChannel {
	if in == nil {
		return nil
	}
	out := new(SharedMemoryChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SharedMemoryChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedMemoryChannelList) DeepCopyInto(out *SharedMemoryChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SharedMemoryChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedMemoryChannelList.
func (in *SharedMemoryChannelList) DeepCopy() *SharedMemoryChannelList {
	if in == nil {
		return nil
	}
	out := new(SharedMemoryChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SharedMemoryChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedMemoryChannelSpec) DeepCopyInto(out *SharedMemoryChannelSpec) {
	*out = *in
	out.VmRef = in.VmRef
	out.RequestRef = in.RequestRef
	out.PvcRef = in.PvcRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedMemoryChannelSpec.
func (in *SharedMemoryChannelSpec) DeepCopy() *SharedMemoryChannelSpec {
	if in == nil {
		return nil
	}
	out := new(SharedMemoryChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedMemoryChannelSpecPvcRef) DeepCopyInto(out *SharedMemoryChannelSpecPvcRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedMemoryChannelSpecPvcRef.
func (in *SharedMemoryChannelSpecPvcRef) DeepCopy() *SharedMemoryChannelSpecPvcRef {
	if in == nil {
		return nil
	}
	out := new(SharedMemoryChannelSpecPvcRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedMemoryChannelSpecRequestRef) DeepCopyInto(out *SharedMemoryChannelSpecRequestRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedMemoryChannelSpecRequestRef.
func (in *SharedMemoryChannelSpecRequestRef) DeepCopy() *SharedMemoryChannelSpecRequestRef {
	if in == nil {
		return nil
	}
	out := new(SharedMemoryChannelSpecRequestRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedMemoryChannelSpecVmRef) DeepCopyInto(out *SharedMemoryChannelSpecVmRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedMemoryChannelSpecVmRef.
func (in *SharedMemoryChannelSpecVmRef) DeepCopy() *SharedMemoryChannelSpecVmRef {
	if in == nil {
		return nil
	}
	out := new(SharedMemoryChannelSpecVmRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedMemoryChannelStatus) DeepCopyInto(out *SharedMemoryChannelStatus) {
	*out = *in
	if in.Sessions != nil {
		in, out := &in.Sessions, &out.Sessions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]SharedMemoryChannelStatusConditionsItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedMemoryChannelStatus.
func (in *SharedMemoryChannelStatus) DeepCopy() *SharedMemoryChannelStatus {
	if in == nil {
		return nil
	}
	out := new(SharedMemoryChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedMemoryChannelStatusConditionsItem) DeepCopyInto(out *SharedMemoryChannelStatusConditionsItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedMemoryChannelStatusConditionsItem.
func (in *SharedMemoryChannelStatusConditionsItem) DeepCopy() *SharedMemoryChannelStatusConditionsItem {
	if in == nil {
		return nil
	}
	out := new(SharedMemoryChannelStatusConditionsItem)
	in.DeepCopyInto(out)
	return out
}
